// flow-typed signature: 85078b13fed44870a6522c7d332ae91f
// flow-typed version: <<STUB>>/lit-html_v1.0.0-rc.2/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lit-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lit-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lit-html/directives/async-append' {
  declare module.exports: any;
}

declare module 'lit-html/directives/async-replace' {
  declare module.exports: any;
}

declare module 'lit-html/directives/cache' {
  declare module.exports: any;
}

declare module 'lit-html/directives/class-map' {
  declare module.exports: any;
}

declare module 'lit-html/directives/guard' {
  declare module.exports: any;
}

declare module 'lit-html/directives/if-defined' {
  declare module.exports: any;
}

declare module 'lit-html/directives/repeat' {
  declare module.exports: any;
}

declare module 'lit-html/directives/style-map' {
  declare module.exports: any;
}

declare module 'lit-html/directives/unsafe-html' {
  declare module.exports: any;
}

declare module 'lit-html/directives/until' {
  declare module.exports: any;
}

declare module 'lit-html/lib/default-template-processor' {
  declare module.exports: any;
}

declare module 'lit-html/lib/directive' {
  declare module.exports: any;
}

declare module 'lit-html/lib/dom' {
  declare module.exports: any;
}

declare module 'lit-html/lib/modify-template' {
  declare module.exports: any;
}

declare module 'lit-html/lib/part' {
  declare module.exports: any;
}

declare module 'lit-html/lib/parts' {
  declare module.exports: any;
}

declare module 'lit-html/lib/render-options' {
  declare module.exports: any;
}

declare module 'lit-html/lib/render' {
  declare module.exports: any;
}

declare module 'lit-html/lib/shady-render' {
  declare module.exports: any;
}

declare module 'lit-html/lib/template-factory' {
  declare module.exports: any;
}

declare module 'lit-html/lib/template-instance' {
  declare module.exports: any;
}

declare module 'lit-html/lib/template-processor' {
  declare module.exports: any;
}

declare module 'lit-html/lib/template-result' {
  declare module.exports: any;
}

declare module 'lit-html/lib/template' {
  declare module.exports: any;
}

declare module 'lit-html/lit-html' {
  declare module.exports: any;
}

declare module 'lit-html/polyfills/template_polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lit-html/directives/async-append.js' {
  declare module.exports: $Exports<'lit-html/directives/async-append'>;
}
declare module 'lit-html/directives/async-replace.js' {
  declare module.exports: $Exports<'lit-html/directives/async-replace'>;
}
declare module 'lit-html/directives/cache.js' {
  declare module.exports: $Exports<'lit-html/directives/cache'>;
}
declare module 'lit-html/directives/class-map.js' {
  declare module.exports: $Exports<'lit-html/directives/class-map'>;
}
declare module 'lit-html/directives/guard.js' {
  declare module.exports: $Exports<'lit-html/directives/guard'>;
}
declare module 'lit-html/directives/if-defined.js' {
  declare module.exports: $Exports<'lit-html/directives/if-defined'>;
}
declare module 'lit-html/directives/repeat.js' {
  declare module.exports: $Exports<'lit-html/directives/repeat'>;
}
declare module 'lit-html/directives/style-map.js' {
  declare module.exports: $Exports<'lit-html/directives/style-map'>;
}
declare module 'lit-html/directives/unsafe-html.js' {
  declare module.exports: $Exports<'lit-html/directives/unsafe-html'>;
}
declare module 'lit-html/directives/until.js' {
  declare module.exports: $Exports<'lit-html/directives/until'>;
}
declare module 'lit-html/lib/default-template-processor.js' {
  declare module.exports: $Exports<'lit-html/lib/default-template-processor'>;
}
declare module 'lit-html/lib/directive.js' {
  declare module.exports: $Exports<'lit-html/lib/directive'>;
}
declare module 'lit-html/lib/dom.js' {
  declare module.exports: $Exports<'lit-html/lib/dom'>;
}
declare module 'lit-html/lib/modify-template.js' {
  declare module.exports: $Exports<'lit-html/lib/modify-template'>;
}
declare module 'lit-html/lib/part.js' {
  declare module.exports: $Exports<'lit-html/lib/part'>;
}
declare module 'lit-html/lib/parts.js' {
  declare module.exports: $Exports<'lit-html/lib/parts'>;
}
declare module 'lit-html/lib/render-options.js' {
  declare module.exports: $Exports<'lit-html/lib/render-options'>;
}
declare module 'lit-html/lib/render.js' {
  declare module.exports: $Exports<'lit-html/lib/render'>;
}
declare module 'lit-html/lib/shady-render.js' {
  declare module.exports: $Exports<'lit-html/lib/shady-render'>;
}
declare module 'lit-html/lib/template-factory.js' {
  declare module.exports: $Exports<'lit-html/lib/template-factory'>;
}
declare module 'lit-html/lib/template-instance.js' {
  declare module.exports: $Exports<'lit-html/lib/template-instance'>;
}
declare module 'lit-html/lib/template-processor.js' {
  declare module.exports: $Exports<'lit-html/lib/template-processor'>;
}
declare module 'lit-html/lib/template-result.js' {
  declare module.exports: $Exports<'lit-html/lib/template-result'>;
}
declare module 'lit-html/lib/template.js' {
  declare module.exports: $Exports<'lit-html/lib/template'>;
}
declare module 'lit-html/lit-html.js' {
  declare module.exports: $Exports<'lit-html/lit-html'>;
}
declare module 'lit-html/polyfills/template_polyfill.js' {
  declare module.exports: $Exports<'lit-html/polyfills/template_polyfill'>;
}
